2023-02-03 11:02:17,728 INFO    MainThread:844969 [wandb_setup.py:_flush():69] setting env: {}
2023-02-03 11:02:17,728 INFO    MainThread:844969 [wandb_setup.py:_flush():69] setting login settings: {}
2023-02-03 11:02:17,729 INFO    MainThread:844969 [wandb_init.py:_log_setup():342] Logging user logs to /home/22842219/Desktop/phd/SemanticParser4Graph/semantic_parser/wandb/run-20230203_110217-29faciio/logs/debug.log
2023-02-03 11:02:17,729 INFO    MainThread:844969 [wandb_init.py:_log_setup():343] Logging internal logs to /home/22842219/Desktop/phd/SemanticParser4Graph/semantic_parser/wandb/run-20230203_110217-29faciio/logs/debug-internal.log
2023-02-03 11:02:17,729 INFO    MainThread:844969 [wandb_init.py:init():375] calling init triggers
2023-02-03 11:02:17,729 INFO    MainThread:844969 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2023-02-03 11:02:17,730 INFO    MainThread:844969 [wandb_init.py:init():424] starting backend
2023-02-03 11:02:17,730 INFO    MainThread:844969 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-02-03 11:02:17,743 INFO    MainThread:844969 [backend.py:ensure_launched():135] starting backend process...
2023-02-03 11:02:17,751 INFO    MainThread:844969 [backend.py:ensure_launched():140] started backend process with pid: 845027
2023-02-03 11:02:17,753 INFO    MainThread:844969 [wandb_init.py:init():429] backend started and connected
2023-02-03 11:02:17,755 INFO    MainThread:844969 [wandb_init.py:init():477] updated telemetry
2023-02-03 11:02:17,755 INFO    MainThread:844969 [wandb_init.py:init():500] communicating current version
2023-02-03 11:02:19,021 INFO    MainThread:844969 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.13.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-02-03 11:02:19,022 INFO    MainThread:844969 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2023-02-03 11:02:49,022 INFO    MainThread:844969 [interface.py:_communicate_run():651] couldn't get run from backend
2023-02-03 11:02:49,023 ERROR   MainThread:844969 [wandb_init.py:init():518] backend process timed out
2023-02-03 11:02:49,023 ERROR   MainThread:844969 [wandb_init.py:init():527] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-02-03 11:02:49,047 ERROR   MainThread:844969 [wandb_init.py:init():801] error
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3.7pytorch1.8new/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 775, in init
    run = wi.init()
  File "/root/anaconda3/envs/py3.7pytorch1.8new/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 531, in init
    backend.cleanup()
  File "/root/anaconda3/envs/py3.7pytorch1.8new/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 167, in cleanup
    self.interface.join()
  File "/root/anaconda3/envs/py3.7pytorch1.8new/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 830, in join
    _ = self._communicate(record)
  File "/root/anaconda3/envs/py3.7pytorch1.8new/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/root/anaconda3/envs/py3.7pytorch1.8new/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
